---
# handlers file for ossec-agent

- name: restart ossec-agent
  service:
    name: "{{ ossec_init_name }}"
    state: restarted
    enabled: yes
  when: not ossec_agent_install_only

- name: restart ossec-server
  shell: |
    /var/ossec/bin/ossec-control restart
  delegate_to: "{{ ossec_server_name }}"
